### ISSUE TITLE
Reference version conflict error 

### ISSUE THREAD

**Issue by JerzyR** [Zastai/MetaBrainz.MusicBrainz#18]
VS Studio wants to load MetaBrainz.common.Json.dll verion 3.0.0 but the latest version is shipped with version 4.0.0
By that it gives error that  MetaBrainz.common.Json.dll  v 3.0.0 could not be loaded

**Comment by Zastai** [comment]
You'll need to give some clearer information than that.
Which version of Visual Studio are you using? (Should probably be 2019.)
What exact error are you getting?

**Comment by JerzyR** [comment]
I have VS 2019 the latest build, and MetaBrainz  installed by CS vi NuGet Package Manager
This is what is installed
MetaBrainz.Common.Json.dll version 4.0.0
MetaBrainz.MusicBrainz.CoverArt.dll version 3.0.0
MetaBrainz.MusicBrainz.DiscId.dll version 2.0.1.0
MetaBrainz.MusicBrainz.dll version 3.0.2.0


When I'm trying to use the library VS goes into a break mode with error message
Could not load or find file MetaBrainz.Common.Json.dll version 3.0.0

Must be something going because it is looking for a version 3.0.0.
Apparently  MetaBrainz.Common.Json.dll  file is in the folder but the version is higher
Please let me know if you need some more info, thanks

**Comment by Zastai** [comment]
OK, welll the CoverArt and MusicBrainz libraries both use version 3.0.0 of the JSON library.
They'll use version 4.0 at some point.

Just because there's a newer version of a package, doesn't mean you have to use it; just downgrade the JSON library to 3.0.0 and it should build and run fine.

**Comment by JerzyR** [comment]
How to downgrade? do  you have download link to version 3?
At Nuget Manager I cannot do that

**Comment by JerzyR** [comment]
Never mind, i found you have releases history, sorry

**Comment by Zastai** [comment]
In the NuGet package manager it should be quite easy, just use the dropdown for the version selection:
![image](https://user-images.githubusercontent.com/13708975/128266143-29ffc229-87e6-4f30-af03-b2e5ce9486ea.png)

Selection 3.0.1 should be fine; only minor and major version bumps could create trouble.

**Comment by JerzyR** [comment]
Maybe this will help
I did installed version 3.0.1 and now I'm getting
Severity	Description	Project	Code	File	Line	Suppression State
Error	Reference required to assembly 'MetaBrainz.Common.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021' containing the type 'IJsonBasedObject'. Add one to your project.	 

Going to install version 3.0.0

**Comment by JerzyR** [comment]
Can you help me out with downloading MetaBrainz.Common.Json.dll version 3.0.0
It seems like version 3.0.0 also requires it but the NuGet Manager somehow does not installs it

**Comment by Zastai** [comment]
NuGet manager, or the package restore, should download it just fine. The package is on nuget.org, so you can get it from there. It should also be on GitHub.

**Comment by JerzyR** [comment]
![metabrainz](https://user-images.githubusercontent.com/37277239/128268265-4a646c84-e1d9-4cfd-86f3-fff20e0d094e.png)

I only get MetaBrainz.Common.Json.dll version 4.0.0 installed with all versions.
Deleted MetaBrainz.Common.Json.dll version 4.0.0 folder and uninstalled the MetaBraiz version 3.0.0
Installed again and also I get MetaBrainz.Common.Json.dll version 4.0.0 installed

**Comment by JerzyR** [comment]
I got it, i thought that it will be installed along with master library but it is not, i did it by installing it separately
