### ISSUE TITLE
Coordinates parsing in Place entity

### ISSUE THREAD

**Issue by ReIaxo** [Zastai/MetaBrainz.MusicBrainz#48]
The Coordinates field can also be a string, including N or E like in 49.551317N, 8.668462E (https://musicbrainz.org/place/2f5c20f1-abfc-45b8-bc75-77a399cdb0cc)

I get this inner exception:
```
{System.InvalidOperationException: Cannot get the value of a token type 'String' as a number.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
   at System.Text.Json.Utf8JsonReader.GetDouble()
   at MetaBrainz.Common.Json.JsonUtils.GetOptionalDouble(Utf8JsonReader& reader)
   at MetaBrainz.MusicBrainz.Json.Readers.CoordinatesReader.ReadObjectContents(Utf8JsonReader& reader, JsonSerializerOptions options)}
```
Here the lines in your code.
https://github.com/Zastai/MetaBrainz.MusicBrainz/blob/2524cc9fa8a1fffe87e864a2aea50f78e172fe29/MetaBrainz.MusicBrainz/Json/Readers/CoordinatesReader.cs#L25C40-L25C40

**Comment by Zastai** [comment]
You're right; the schema has these as just text.
While the MB website does sanitize the values when you enter them, , the database will continue to have unsanitized contents.

Now deciding whether I should just change the properties to strings (requiring a major version bump because that's a breaking change), or add `LatitudeText` and `LongitudeText`, with the non-text versions marked `[Obsolete]` and throwing when the text isn't a valid number. Either way, I don't think it's worth it to try and handle specific types of text.

**Comment by Zastai** [comment]
Although strangely I cannot reproduce the error you report even though it makes perfect sense given what the data looks like on the main site.

A `LookupPlace(new Guid("2f5c20f1-abfc-45b8-bc75-77a399cdb0cc"))` causes a request to [this link](https://musicbrainz.org/ws/2/place/2f5c20f1-abfc-45b8-bc75-77a399cdb0cc?fmt=json) which returns a JSON response that has the latitude/longitude as numbers, not text:

```json
{
      "area": {
            "disambiguation": "",
            "name": "Weinheim",
            "type-id": null,
            "type": null,
            "sort-name": "Weinheim",
            "id": "863c0b47-4fff-4561-85b1-33450f20b3bb"
      },
      "coordinates": {
            "longitude": 8.668462,
            "latitude": 49.551317
      },
      "life-span": {
            "end": null,
            "ended": false,
            "begin": null
      },
      "disambiguation": "",
      "name": "Café Central",
      "type": "Venue",
      "address": "Bahnhofstraße 19, 69469 Weinheim, Germany",
      "type-id": "cd92781a-a73f-30e8-a430-55d7521338db",
      "id": "2f5c20f1-abfc-45b8-bc75-77a399cdb0cc"
}
```

**Comment by ReIaxo** [comment]
I get the error when I use FindPlaces(name,25,0,true). Maybe that is different from LookupPlace(..)? Or maybe it has to do with another mirror or Version of the API of MusicBrainz? Does MusicBrainz use mirrors or have different API Versions running? Can I config this in your API client?

Outer Exception is:
```
Exception has occurred: CLR/System.Text.Json.JsonException
An unhandled exception of type 'System.Text.Json.JsonException' occurred in System.Private.CoreLib.dll: 'Failed to deserialize the 'places' property.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidOperationException : Cannot get the value of a token type 'String' as a number.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
   at System.Text.Json.Utf8JsonReader.GetDouble()
   at MetaBrainz.Common.Json.JsonUtils.GetOptionalDouble(Utf8JsonReader& reader)
   at MetaBrainz.MusicBrainz.Json.Readers.CoordinatesReader.ReadObjectContents(Utf8JsonReader& reader, JsonSerializerOptions options)
```

**Comment by Zastai** [comment]
Aha! Yes, now I can reproduce it.

Looks like [that query](https://musicbrainz.org/ws/2/place/?query=Café%20Central&limit=25&fmt=json) indeed uses strings, but those strings just contain a number, so I will probably be able to keep the properties as doubles.

**Comment by Zastai** [comment]
Looks like this is a regression of [MBS-10411](https://tickets.metabrainz.org/browse/MBS-10411) as well; will reopen that.

**Comment by ReIaxo** [comment]
Thank you for fixing this. When will the new package, containing this fix, be publised?

**Comment by Zastai** [comment]
Published now. May take a little while to propagate through nuget.org

**Comment by ReIaxo** [comment]
Works like a charm. Thank you.
